export const defaultFilter = {
  organizer: [],
  title: '',
  description: '',
  beginningDayFrom: '',
  beginningDayTo: '',
  beginningTimeFrom: '',
  beginningTimeTo: '',
  endingDayFrom: '',
  endingDayTo: '',
  endingTimeFrom: '',
  endingTimeTo: '',
  minParticipants: '',
  maxParticipants: '',
  sport: '',
  sportLevelFrom: '',
  sportLevelTo: '',
  type: [],
  opponent: [],
  address: [],
  kind: [],
  priceFrom: '',
  priceTo: '',
  summonGroup: [],
  summonUsers: [],
  coOrganizer: [],
  status: ['Organized'],
};
