export const defaultColumns = [
  { name: 'datasheet_index', width: 100, visible: true },
  { name: 'datasheet_external_id', width: 150, visible: true },
  { name: 'datasheet_organizer', width: 150, visible: true },
  { name: 'datasheet_title', width: 150, visible: true },
  { name: 'datasheet_description', width: 300, visible: true },
  { name: 'datasheet_beginning_day', width: 150, visible: true },
  { name: 'datasheet_beginning_hour', width: 150, visible: true },
  { name: 'datasheet_ending_day', width: 150, visible: true },
  { name: 'datasheet_ending_hour', width: 150, visible: true },
  { name: 'datasheet_min_participants', width: 150, visible: true },
  { name: 'datasheet_max_participants', width: 150, visible: true },
  { name: 'datasheet_sport', width: 150, visible: true },
  { name: 'datasheet_sport_level_from', width: 150, visible: true },
  { name: 'datasheet_sport_level_to', width: 150, visible: true },
  { name: 'datasheet_type', width: 200, visible: true },
  { name: 'datasheet_opponent', width: 200, visible: true },
  { name: 'datasheet_address', width: 300, visible: true },
  { name: 'datasheet_kind', width: 150, visible: true },
  { name: 'datasheet_price', width: 100, visible: true },
  { name: 'datasheet_summon_group', width: 300, visible: true },
  { name: 'datasheet_summon_user', width: 150, visible: true },
  { name: 'datasheet_co_organizers', width: 300, visible: true },
  { name: 'datasheet_status', width: 150, visible: true },
];
