
// APP

export const UPDATE_LOGIN_STATUS = 'UPDATE_LOGIN_STATUS';

// REGISTER

export const UPDATE_REGISTER_AVATAR = 'UPDATE_REGISTER_AVATAR';
export const UPDATE_REGISTER_PSEUDO = 'UPDATE_REGISTER_PSEUDO';
export const UPDATE_REGISTER_EMAIL = 'UPDATE_REGISTER_EMAIL';
export const UPDATE_REGISTER_PASSWORD1 = 'UPDATE_REGISTER_PASSWORD1';
export const UPDATE_REGISTER_PASSWORD2 = 'UPDATE_REGISTER_PASSWORD2';
export const UPDATE_REGISTER_PHONE = 'UPDATE_REGISTER_PHONE';
export const UPDATE_REGISTER_DESCRIPTION = 'UPDATE_REGISTER_DESCRIPTION';
export const UPDATE_REGISTER_BIRTHDAY = 'UPDATE_REGISTER_BIRTHDAY';
export const UPDATE_REGISTER_PROFILETYPE = 'UPDATE_REGISTER_PROFILETYPE';
export const UPDATE_REGISTER_FROM = 'UPDATE_REGISTER_FROM';
export const UPDATE_REGISTER_RESET = 'UPDATE_REGISTER_RESET';
export const ADD_REGISTER_SUBACCOUNTS= 'ADD_REGISTER_SUBACCOUNTS';
export const UPDATE_REGISTER_SUBACCOUNTS= 'UPDATE_REGISTER_SUBACCOUNTS';
export const UPDATE_REGISTER_ERRORS_PSEUDO= 'UPDATE_REGISTER_ERRORS_PSEUDO';
export const UPDATE_REGISTER_ERRORS_EMAIL = 'UPDATE_REGISTER_ERRORS_EMAIL';
export const UPDATE_REGISTER_SUBACCOUNT_CREATION = 'UPDATE_REGISTER_SUBACCOUNT_CREATION'; 

// LOGIN

export const UPDATE_LOGIN_PSEUDO = 'UPDATE_LOGIN_PSEUDO';
export const UPDATE_LOGIN_PASSWORD = 'UPDATE_LOGIN_PASSWORD';
export const UPDATE_ISEMAILVALIDATED = 'UPDATE_ISEMAILVALIDATED';
export const UPDATE_IS_PROFILE_FROM_LOGIN = 'UPDATE_IS_PROFILE_FROM_LOGIN';
export const LOGGED_IN_FROM_PAGE = 'LOGGED_IN_FROM_PAGE';
export const UPDATE_LOGIN_RESET = 'UPDATE_LOGIN_RESET';

// SMALL TUTORIAL 
export const UPDATE_SHOWN_TUTORIAL = 'UPDATE_SHOWN_TUTORIAL';
export const UPDATE_CURRENT_TUTORIAL = 'UPDATE_CURRENT_TUTORIAL';

// SPORTUNITY
export const UPDATE_SPORTUNITY_ID = 'UPDATE_SPORTUNITY_ID';
export const UPDATE_NEXT_TO_SPORTUNITY = 'UPDATE_NEXT_TO_SPORTUNITY';

// PROFILE

export const UPDATE_PROFILE_AVATAR = 'UPDATE_PROFILE_AVATAR';
export const UPDATE_PROFILE_FIRST_NAME = 'UPDATE_PROFILE_FIRST_NAME';
export const UPDATE_PROFILE_LAST_NAME = 'UPDATE_PROFILE_LAST_NAME';
export const UPDATE_PROFILE_USERNAME = 'UPDATE_PROFILE_USERNAME';
export const UPDATE_PROFILE_DESCRIPTION = 'UPDATE_PROFILE_DESCRIPTION';
export const UPDATE_PROFILE_SEX = 'UPDATE_PROFILE_SEX';
export const UPDATE_PROFILE_BIRTHDAY = 'UPDATE_PROFILE_BIRTHDAY';
export const UPDATE_PROFILE_LANGUAGES = 'UPDATE_PROFILE_LANGUAGES';
export const UPDATE_PROFILE_SPORTS = 'UPDATE_PROFILE_SPORTS';
export const UPDATE_PROFILE_ADDRESS = 'UPDATE_PROFILE_ADDRESS';
export const UPDATE_PROFILE_PUBLIC_ADDRESS = 'UPDATE_PROFILE_PUBLIC_ADDRESS';
export const UPDATE_PROFILE_HIDE_MY_AGE = 'UPDATE_PROFILE_HIDE_MY_AGE';
export const UPDATE_PROFILE_EMAIL = 'UPDATE_PROFILE_EMAIL';
export const GET_INITIAL_PROFILE = 'GET_INITIAL_PROFILE';
export const RESET_PROFILE_FORMS = 'RESET_PROFILE_FORMS';
export const UPDATE_STEPS_COMPLETED = 'UPDATE_STEPS_COMPLETED';
export const UPDATE_STEPS_PERCENTAGE = 'UPDATE_STEPS_PERCENTAGE';
export const UPDATE_NEXT_STEP_TO_DO = 'UPDATE_NEXT_STEP_TO_DO';
export const UPDATE_SPORTUNITY_SEARCH_SPORT = 'UPDATE_SPORTUNITY_SEARCH_SPORT'
export const UPDATE_SPORTUNITY_SEARCH_SPORT_NAME = 'UPDATE_SPORTUNITY_SEARCH_SPORT_NAME'
export const UPDATE_SPORTUNITY_SEARCH_LOCATION = 'UPDATE_SPORTUNITY_SEARCH_LOCATION'
export const UPDATE_SPORTUNITY_SEARCH_FREE_ONLY = 'UPDATE_SPORTUNITY_SEARCH_FREE_ONLY'
export const UPDATE_SPORTUNITY_SEARCH_DISTANCE_RANGE = 'UPDATE_SPORTUNITY_SEARCH_DISTANCE_RANGE'
export const UPDATE_SPORTUNITY_SEARCH_DATE_FROM = 'UPDATE_SPORTUNITY_SEARCH_DATE_FROM'
export const UPDATE_SPORTUNITY_SEARCH_DATE_TO = 'UPDATE_SPORTUNITY_SEARCH_DATE_TO'
export const UPDATE_SPORTUNITY_SEARCH_HOUR_FROM = 'UPDATE_SPORTUNITY_SEARCH_HOUR_FROM'
export const UPDATE_SPORTUNITY_SEARCH_HOUR_TO = 'UPDATE_SPORTUNITY_SEARCH_HOUR_TO'
export const UPDATE_SPORTUNITY_SEARCH_AGE_RESTRICTION = 'UPDATE_SPORTUNITY_SEARCH_AGE_RESTRICTION';
export const UPDATE_SPORTUNITY_SEARCH_SEX_RESTRICTION = 'UPDATE_SPORTUNITY_SEARCH_SEX_RESTRICTION';

export const UPDATE_MY_EVENT_FILTER = 'UPDATE_MY_EVENT_FILTER'
export const UPDATE_MY_EVENT_RESET_FILTER = 'UPDATE_MY_EVENT_RESET_FILTER'  
export const UPDATE_MY_EVENT_USER_FILTER = 'UPDATE_MY_EVENT_USER_FILTER'
export const UPDATE_MY_EVENT_SPORTUNITY_TYPE_FILTER = 'UPDATE_MY_EVENT_SPORTUNITY_TYPE_FILTER'
export const UPDATE_MY_EVENT_SPORT_FILTER = 'UPDATE_MY_EVENT_SPORT_FILTER'
export const UPDATE_MY_EVENT_SPORT_LEVELS_FILTER = 'UPDATE_MY_EVENT_SPORT_LEVELS_FILTER'
export const UPDATE_MY_EVENT_DATE_FROM_FILTER = 'UPDATE_MY_EVENT_DATE_FROM_FILTER'
export const UPDATE_MY_EVENT_DATE_TO_FILTER = 'UPDATE_MY_EVENT_DATE_TO_FILTER'
export const UPDATE_MY_EVENT_LOCATION_FILTER = 'UPDATE_MY_EVENT_LOCATION_FILTER'
export const UPDATE_MY_EVENT_ORGANIZERS_FILTER = 'UPDATE_MY_EVENT_ORGANIZERS_FILTER'
export const UPDATE_MY_EVENT_OPPONENTS_FILTER = 'UPDATE_MY_EVENT_OPPONENTS_FILTER'
export const UPDATE_MY_EVENT_SELECTED_FILTERS = 'UPDATE_MY_EVENT_SELECTED_FILTERS'
export const UPDATE_MY_EVENT_FILTER_HAS_CHANGED = 'UPDATE_MY_EVENT_FILTER_HAS_CHANGED'
export const UPDATE_MY_EVENT_SELECTED_CLUBS_ADD = 'UPDATE_MY_EVENT_SELECTED_CLUBS_ADD';
export const UPDATE_MY_EVENT_SELECTED_CLUBS_REMOVE = 'UPDATE_MY_EVENT_SELECTED_CLUBS_REMOVE';
export const UPDATE_MY_EVENT_SELECTED_CLUBS_CLEAR = 'UPDATE_MY_EVENT_SELECTED_CLUBS_CLEAR';

export const UPDATE_MY_CIRCLE_FILTER = 'UPDATE_MY_CIRCLE_FILTER'
export const UPDATE_MY_CIRCLE_RESET_FILTER = 'UPDATE_MY_CIRCLE_RESET_FILTER'
export const UPDATE_MY_CIRCLE_SPORT_FILTER = 'UPDATE_MY_CIRCLE_SPORT_FILTER'
export const UPDATE_MY_CIRCLE_LOCATION_FILTER = 'UPDATE_MY_CIRCLE_LOCATION_FILTER'
export const UPDATE_MY_CIRCLE_TYPE_FILTER = 'UPDATE_MY_CIRCLE_TYPE_FILTER'
export const UPDATE_MY_CIRCLE_USER_FILTER = 'UPDATE_MY_CIRCLE_USER_FILTER'
export const UPDATE_MY_CIRCLE_SELECTED_FILTERS = 'UPDATE_MY_CIRCLE_SELECTED_FILTERS'
export const UPDATE_MY_CIRCLE_NAME_COMPLETION = 'UPDATE_MY_CIRCLE_NAME_COMPLETION'
export const UPDATE_MY_CIRCLE_SEARCH_CODE = 'UPDATE_MY_CIRCLE_SEARCH_CODE'

//Venue
export const VENUE_UPDATE_NAME = 'VENUE_UPDATE_NAME'
export const VENUE_UPDATE_ADDRESS = 'VENUE_UPDATE_ADDRESS'
export const VENUE_UPDATE_CITY = 'VENUE_UPDATE_CITY'
export const VENUE_UPDATE_COUNTRY = 'VENUE_UPDATE_COUNTRY'
export const VENUE_RESET_FORM = 'VENUE_RESET_FORM'
export const VENUE_UPDATE_FORM = 'VENUE_UPDATE_FORM'

//Facility
export const FACILITY_SET_VENUE_ID = 'FACILITY_SET_VENUE_ID'
export const FACILITY_SET_VENUE = 'FACILITY_SET_VENUE'
export const FACILITY_SET_FACILITIES = 'FACILITY_SET_FACILITIES'
export const FACILITY_SET_FACILITY_ID = 'FACILITY_SET_FACILITY_ID'
export const FACILITY_SET_PHOTO = 'FACILITY_SET_PHOTO'
export const FACILITY_UPDATE_FACILITY_NAME = 'FACILITY_UPDATE_FACILITY_NAME'
export const FACILITY_ADD_SPORT = 'FACILITY_ADD_SPORT'
export const FACILITY_ADD_SLOT = 'FACILITY_ADD_SLOT'
export const FACILITY_ADD_AUTHORIZED_MANAGERS = 'FACILITY_ADD_AUTHORIZED_MANAGERS'
export const FACILITY_ADD_FACILITY = 'FACILITY_ADD_FACILITY'
export const FACILITY_RESET_FACILITY = 'FACILITY_RESET_FACILITY'
export const FACILITY_SET_FACILITY = 'FACILITY_SET_FACILITY'
export const FACILITY_DELETE_SPORT = 'FACILITY_DELETE_SPORT'
export const FACILITY_DELETE_SLOT = 'FACILITY_DELETE_SLOT'
export const FACILITY_DELETE_AUTHORIZED_MANAGERS = 'FACILITY_DELETE_AUTHORIZED_MANAGERS'

//Global
export const GLOBAL_SET_LANGUAGE = 'GLOBAL_SET_LANGUAGE'
export const GLOBAL_SET_SITE_OPENED = 'GLOBAL_SET_SITE_OPENED'
export const GLOBAL_SET_USER_COUNTRY = 'GLOBAL_SET_USER_COUNTRY';
export const GLOBAL_SET_USER_CURRENCY = 'GLOBAL_SET_USER_CURRENCY';
export const GLOBAL_SET_USER_LOCATION = 'GLOBAL_SET_USER_LOCATION';
export const GLOBAL_SET_USER_CITY = 'GLOBAL_SET_USER_CITY';

//Composition
export const COMPOSITION_UPDATE_POSITION_ADD = 'COMPOSITION_UPDATE_POSITION_ADD'
export const COMPOSITION_UPDATE_POSITION_UPDATE = 'COMPOSITION_UPDATE_POSITION_UPDATE'
export const COMPOSITION_UPDATE_POSITION_REMOVE = 'COMPOSITION_UPDATE_POSITION_REMOVE'
export const COMPOSITION_UPDATE_POSITION_CLEAR = 'COMPOSITION_UPDATE_POSITION_CLEAR'
export const COMPOSITION_UPDATE_ELEMENT = 'COMPOSITION_UPDATE_ELEMENT'
